In [1]:
import numpy as np

In [3]:
np.__version__

'1.14.3'

In [4]:
import array
L=list(range(10))
M=list(range(5))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
a=array.array('i',L)

In [6]:
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating Arrays from Python Lists

In [7]:
a=np.array([1, 4, 2, 5, 3])
a

array([1, 4, 2, 5, 3])

In [8]:
#Numpy Construted as array should contin same data type 
#else it will upcasets like in ex. decimal points
b=np.array([3.14, 4, 2, 3])
b

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
#as per your Requirement you can mention data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
#NumPy arrays can explicitly be multidimensional
np.array([range(i, i+3) for i in [1, 3, 4]])

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

Creating Arrays from Scratch

In [15]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((4, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.51583381, 0.70787472, 0.24002294],
       [0.09003105, 0.99267197, 0.63898367],
       [0.18133705, 0.71854352, 0.96249688]])

In [22]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.51945164, 0.9180837 , 0.78666263],
       [0.64593307, 0.77552697, 0.77872918],
       [0.0772473 , 0.73456184, 0.81628747]])

In [23]:
#Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 9, 5],
       [8, 2, 2],
       [1, 2, 8]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

NumPy Array Attributes
-Determining the size, shape, memory consumption, and data types of arrays

In [37]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(20, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(4, 4, 5)) # Three-dimensional array

In [33]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (4, 4, 5)
x3 size:  80


In [38]:
x1

array([12, 15,  0,  3,  3,  7])

In [39]:
print("dtype:", x3.dtype)

dtype: int32


In [40]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 320 bytes


In [41]:
x1

array([12, 15,  0,  3,  3,  7])

In [42]:
x1[0]

12

In [43]:
x1[3]

3

In [44]:
x1[-2]

3

In [45]:
x1[-4]

0

In [46]:
x2

array([[9, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7]])

In [47]:
x2[0, 0]

9

In [48]:
x2[2, 0]

8

In [49]:
x2[2, -1]

7

In [51]:
#You can also modify values using any of the above index notation
x2[0, 0]=15

In [52]:
x2[0, 0]

15

In [53]:
#unlike Python lists, NumPy arrays have a fixed type
x1

array([12, 15,  0,  3,  3,  7])

In [55]:
x1[2]=3.14
x1

array([12, 15,  3,  3,  3,  7])

# Array Slicing: Accessing Subarrays

In [57]:
#x[start:stop:step] Default start =0, Stop=Size of the dimention, step=1
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [59]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [60]:
x[4:7] # middle subarray

array([4, 5, 6])

In [61]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [62]:
x[::3] 

array([0, 3, 6, 9])

In [63]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
x[::-2]

array([9, 7, 5, 3, 1])

In [65]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

Multidimensional subarrays

In [67]:
#Multidimensional slices work in the same way, with multiple slices separated by commas.
x2

array([[15,  3,  5,  2],
       [ 4,  7,  6,  8],
       [ 8,  1,  6,  7]])

In [68]:
x2[:2, :3] # two rows, three columns

array([[15,  3,  5],
       [ 4,  7,  6]])

In [69]:
x2[:3, :2]

array([[15,  3],
       [ 4,  7],
       [ 8,  1]])

In [70]:
x2[:3, ::2] # all rows, every other column

array([[15,  5],
       [ 4,  6],
       [ 8,  6]])

In [72]:
x2[:3, ::3] #x2[:4, ::3] this also work even 4th row doesn't exit

array([[15,  2],
       [ 4,  8],
       [ 8,  7]])

In [73]:
#Finally, subarray dimensions can even be reversed together:
x2[::-1, ::-1]

array([[ 7,  6,  1,  8],
       [ 8,  6,  7,  4],
       [ 2,  5,  3, 15]])

In [74]:
#For Indexing array start from 0 and slicing it start from 1 its for my understanding
#just like list

Accessing array rows and columns.

In [75]:
x2

array([[15,  3,  5,  2],
       [ 4,  7,  6,  8],
       [ 8,  1,  6,  7]])

In [76]:
print(x2[:, 0]) # first column of x2

[15  4  8]


In [78]:
print(x2[:, 3])

[2 8 7]


In [79]:
print(x2[0, :]) # first row of x2

[15  3  5  2]


In [81]:
print(x2[0]) # equivalent to x2[0, :]

[15  3  5  2]


In [82]:
print(x2[1])

[4 7 6 8]


In [83]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[15  3]
 [ 4  7]]


In [84]:
#If we now modify this subarray, the original array is not touched
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  3]
 [ 4  7]]


In [85]:
x2

array([[15,  3,  5,  2],
       [ 4,  7,  6,  8],
       [ 8,  1,  6,  7]])

Reshaping of Arrays

In [86]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [88]:
x

array([1, 2, 3])

In [90]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [91]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

In [94]:
#Done Through np.concatenate, np.vstack, and np.hstack
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [95]:
#You can also concatenate more than two arrays at once:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [98]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])

In [97]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [102]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [103]:
#For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
#(vertical stack) and np.hstack (horizontal stack) functions
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])

In [104]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [105]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])